### ISSUE TITLE
Replays saved at different tickrate

### ISSUE THREAD

**Issue by Chabinka** [jonitaikaponi/ckSurf#10]
Not sure if this is a bug or if there's a configuration to set replay tickrate, though our server was initially 102 tick when the timer was installed and changed later to 85 tick, though it seems replays are still recorded at 102 tick.

**Comment by jonitaikaponi** [comment]
85 tick? Kind of a weird amount.
The plugin currently rounds the announced tickrate to 64, 102 or 128.
Are your record bots performing normally, or are they laggy?

2015-07-10 0:27 GMT+03:00 Jake E. <notifications@github.com>:

**Comment by Chabinka** [comment]
The bots are quite jittery during replays
