### ISSUE TITLE
Disable All Chat Tags ConVar

### ISSUE THREAD

**Issue by gamemann** [jonitaikaponi/ckSurf#13]
Hello, this is more of a suggestion. Is there anyway to implement a ConVar that disables chat tags completely? I am using another plugin to handle chat tags. I had to disable all the ConVars that handle chat tags (including "ck_point_system") to get the other plugin working properly. I need "ck_point_system" to be enabled without the chat tags. Therefore, a ConVar that disables the plugin handling the chat would be appreciated (having them enabled in the scoreboard is fine).

Personally, I would check if the ConVar is enabled here and return the Plugin_Handle if it isn't enabled:
https://github.com/jonitaikaponi/ckSurf/blob/master/csgo/addons/sourcemod/scripting/ckSurf/hooks.sp#L359

However, I'm sure you know more about this plugin than I do.

Thanks for reading.

**Comment by jonitaikaponi** [comment]
Hey,

Yeah that is easy to do. I'll add it into the next update, which I'll
hopefully release next week.

If you in the mean time want to do a quick fix and remove all chat
processing by ckSurf, just add:

return Plugin_Continue;

right into the start of the method that you linked. Compiling the plugin
after that will give you a warning about unreachable code, but you can just
ignore that.

Keep in mind that ckSurf only compiles on the 1.6 SM compiler.

Cheers,
Joni

2015-07-24 18:19 GMT+03:00 Christian Deacon <notifications@github.com>:

**Comment by gamemann** [comment]
Alright, thank you!
