### ISSUE TITLE
[Suggestion] Styles

### ISSUE THREAD

**Issue by gamemann** [jonitaikaponi/ckSurf#14]
Hello, I have another suggestion for this plugin. In other timer plugins, there are styles. For example, "w" only.

I am using this plugin for my Bunny Hop server since it mostly works for Bunny Hop as well. However, in my opinion, styles are somewhat important in Bunny Hop.

If this cannot be made, I understand but I am just throwing the idea out there for the future. The plugin appears to work fine on Bunny Hop servers besides missing the styles feature.

Thanks.

**Comment by jonitaikaponi** [comment]
Hey,

Might add some styles for surf later, but won't be supporting bhop.
24.7.2015 20.13 "Christian Deacon" <notifications@github.com> kirjoitti:
