### ISSUE TITLE
Request: TP back to prior zone

### ISSUE THREAD

**Issue by karlbonitz** [jonitaikaponi/ckSurf#16]
Hello Joni, I hope all is well. This is more of a feature request / lacking feature. In an older surf plugin there used to be another zone type that would teleport the player back to the current stage being surfed. This was used in case of a map with bad teleport zones such as surf_colors_beta1. Instead of the played bypassing or being able to skip areas, it would TP them back to the start of the current stage.

Any possibility this could be added? Keep up the great work as this plugin is awesome! Everyone loves it!

**Comment by jonitaikaponi** [comment]
Hey,

You can use checker zones to teleport players back to start of the stage that they are currently in.

As for surf_colors_beta1, it wouldn't work if the player skips a whole stage, and never gets tagged to the skipped stage.
