### ISSUE TITLE
!cp and !prac - ability to teleport and register time

### ISSUE THREAD

**Issue by karlbonitz** [jonitaikaponi/ckSurf#17]
Joni apparently there is a glitch with !cp and !prac that allows a player to utilize these commands and use them to create a checkpoint in the end zone. Once they have done this they can somehow TP to it and gain 0.7 second times on most maps.

Is there a way / cvar to disable these features as I would like to remove them from my server before this happens again. I dug through all the configs and couldn't find anything.

Thank you!

**Comment by jonitaikaponi** [comment]
This has been fixed over a month ago.
11.8.2015 6.43 "karlbonitz" <notifications@github.com> kirjoitti:

**Comment by karlbonitz** [comment]
Hi Joni, thanks for the reply. I received a report tonight that one of the members of my server was able to still achieve a time by utilizing the old glitch. I have made sure I am completely updated on all of the plugin files.

**Comment by jonitaikaponi** [comment]
How did it happen?
11.8.2015 7.46 "karlbonitz" <notifications@github.com> kirjoitti:

**Comment by jonitaikaponi** [comment]
You can check latest records in your database, or by writing !latest to see
if someone actually made a 0:07 record.

2015-08-11 7:47 GMT+03:00 Joni Sjöstedt <joni.sjostedt@gmail.com>:
