### ISSUE TITLE
Database.cfg isn't there!

### ISSUE THREAD

**Issue by Gosuo** [jonitaikaponi/ckSurf#18]
I downloaded the zip and put everything into my csgo folder. Right after that, I realised there is no database.cfg? Or is it just for me? I can't see it on github either. Any suggestions?

**Comment by marcowmadeira** [comment]
That file is part of SourceMod itself, after installing the SourceMod on your server you should find it on the following path: addons/sourcemod/configs/databases.cfg

**Comment by Gosuo** [comment]
Uhm, forgot to install SourceMod... xD Thank you for the quick answer.
Resetted my server for a few days.

**Comment by Gosuo** [comment]
I hope I helped some people with this stupid mistake. xD
