### ISSUE TITLE
No Points are given

### ISSUE THREAD

**Issue by janssenb** [jonitaikaponi/ckSurf#2]
Players are complaining that they dont getting points for completing maps.
So i took a look at the log files and found this:

L 06/26/2015 - 14:03:01: SourceMod error session started
L 06/26/2015 - 14:03:01: Info (map "surf_how2surf") (file "errors_20150626.log")
L 06/26/2015 - 14:03:01: [SM] Native "ResetPack" reported: Invalid data pack handle 1 (error 1)
L 06/26/2015 - 14:03:01: [SM] Displaying call stack trace for plugin "ckSurf.smx":
L 06/26/2015 - 14:03:01: [SM]   [0]  Line 2316, ckSurf/sql.sp::SQL_UpdateRecordProCallback()
L 06/26/2015 - 14:05:11: Error log file session closed.
L 06/26/2015 - 16:23:52: SourceMod error session started
L 06/26/2015 - 16:23:52: Info (map "surf_colours") (file "errors_20150626.log")
L 06/26/2015 - 16:23:52: [SM] Native "ResetPack" reported: Invalid data pack handle 2 (error 7)
L 06/26/2015 - 16:23:52: [SM] Displaying call stack trace for plugin "ckSurf.smx":
L 06/26/2015 - 16:23:52: [SM]   [0]  Line 2316, ckSurf/sql.sp::SQL_UpdateRecordProCallback()

Corresponding Map Records :

Last map records:
2015-06-26 16:23:52: HaslmeierFx on surf_colours - Time 11:05:36
2015-06-26 14:03:01: HaslmeierFx on surf_how2surf - Time 04:34:36

I guess there is a problem with mysql ? Everything else is working fine.

Thank you!

**Comment by jonitaikaponi** [comment]
Hey,

Thanks for the report!

My bad, fixed in the new version.
Luckily no points were lost, as the error was caused after inserting the
record data and selecting information for the announcements afterwards.

2015-06-26 17:35 GMT+03:00 janssenb <notifications@github.com>:

**Comment by janssenb** [comment]
Points are set to 0 for all players - just checked the mysql database via phpmyadmin.
Thanks for your fast update.

(All Maps are in my mapcycle.txt) - do you have an idea what went wrong ?

**Comment by jonitaikaponi** [comment]
Weird, do the players have times in ck_playertimes? If so, the points
should update when they come back on the server.

2015-06-26 20:54 GMT+03:00 janssenb <notifications@github.com>:

**Comment by janssenb** [comment]
![ck_playertimes](https://cloud.githubusercontent.com/assets/6626215/8383941/a70b8302-1c3d-11e5-9a34-1aa20ba87ff9.PNG)

Yes, they do.
Ok i'll check when they are back on the server.

Thank you!
