### ISSUE TITLE
211-212 plugin-breaking update

### ISSUE THREAD

**Issue by XEROpw** [jonitaikaponi/ckSurf#22]
Plugin does not load, I've updated my sourcemod/metamod files, and even wipe-clean-installed the server and it works fine, except for when cksurf.smx is loaded.

Sourcemod log is useless, no errors displayed, while srcds console hangs on loading the plugin and is not responding.
![image](https://cloud.githubusercontent.com/assets/13028050/9895010/6b3b1ea0-5bf8-11e5-8838-bb0bfa14b956.png)

**Comment by pandaman09** [comment]
Check your errors_UNIXTIME.log in csgo/addons/sourcemod/logs
I had issues with CK surf loading also but after making sure that mapcycle.txt was in the server along with installing the newest version (via the download button on the right side of github), I have gotten it to load.

**Comment by jonitaikaponi** [comment]
Check your sourcemod error log in addons/sourcemod/logs ...

Plugin seems to be working fine for me.

**Comment by XEROpw** [comment]
Like I said, the error log is empty. Server loads and works fine without cksurf, once I put it in, it just gets stuck on loading the plugin and never loads the server. Again, the logs are empty, everything from meta to sm is loaded, all extensions are fine, mysql connection is fully established, only the cksurf plugin breaks the server.

**Comment by jonitaikaponi** [comment]
Then there must be something wrong with your install. Maybe you are missing
a file like pandaman said, even though missing files should give you errors.

2015-09-16 13:48 GMT+03:00 XEROpw <notifications@github.com>:

**Comment by XEROpw** [comment]
I have performed about 20 clean installs, and each time the only thing keeping the server from running is cksurf.smx; anyway, server works fine with meta 1.11 or 1.10, sm 1.7.3 or 1.8/1.81, and a multitude of combinations of these versions, but the common denominator is cksurf - once I move it to disabled, it works great. 

I've used cksurf all up until this update, but this new csgo update destroyed cksurf for me. Also, table structure is the same as always, and all sm/meta/stripper files are good, as well as all cksurf dependencies. All maps work, server only hangs when cksurf is put in the plugins folder.

**Comment by XEROpw** [comment]
Also, no issues with databases, other plugins work fine, in both mysql or sqlite drivers. Anyway, I have about 10 other surf servers of my competition down, so at least I know I'm not the only one with the problem.

**Comment by XEROpw** [comment]
Another issue is when I compile ckSurf, sql include is calling topmenu in a compiler-unfriendly way.

**Comment by XEROpw** [comment]
It seems after re-coding it for sm 1.8.1 the issues are gone, I also re-coded the rank system, and made everything a little more dynamic. This was a great base to fork from, though, so thank you @jonitaikaponi for this great open-source resource.

Some competition is still down, which I think is hilarious and I'm back up. Kind regards.
