### ISSUE TITLE
Threaded SQL Needed

### ISSUE THREAD

**Issue by gamemann** [jonitaikaponi/ckSurf#24]
Hello, I would like to report an issue with CKSurf. Today, I started receiving this error on my European Surf Timer servers:
L 10/14/2015 - 23:24:18: [SM] Plugin encountered error 30: Script execution timed out
L 10/14/2015 - 23:24:18: [SM] Native "GetAdminTopMenu" reported: Error encountered while processing a dynamic native
L 10/14/2015 - 23:24:18: [SM] Displaying call stack trace for plugin "ckSurf.smx":
L 10/14/2015 - 23:24:18: [SM]   [0]  Line 2036, C:\ckSurf\ckSurf\csgo\addons\sourcemod\scripting\ckSurf.sp::OnPluginStart()

After spending time updating SourceMod & MetaMod along with CKSurf, nothing was fixed. Therefore, I decided to duplicate the database onto my home server. The issue still occurred. However, I started emptying tables for testing and when I emptied "ck_playerrank", the issue was fixed. I looked into this further and found these lines located in the sql.sp file (when the database is set up):
    if (SQL_FastQuery(g_hDb, "SELECT * FROM playerrank;") && !SQL_FastQuery(g_hDb,        "SELECT * FROM ck_playerrank;"))
		db_renameTables();
	else
		if (!SQL_FastQuery(g_hDb, "SELECT * FROM playerrank;") && !SQL_FastQuery(g_hDb, "SELECT * FROM ck_playerrank;"))
			db_createTables();

When I commented out these lines of code, the issue stopped. As expected, SQL_FastQuery isn't threaded. Therefore, the server needs to wait for the query to finish. My MySQL server is located in the United States, the game servers are located in Europe. With the table having 200,000 rows, it takes a long time for the query to finish. Before the query can finish, SourceMod thinks the plugin "timed out".

I did some testing and added a new command:
Additions:
CKSurf.sp:
RegConsoleCmd("sm_query", Command_Query, "[ckSurf] Query MySQL");

Commands.sp:
public Action:Command_Query(client, args)
{
	decl String:arg1[256];
	
	GetCmdArg(1, arg1, sizeof(arg1));
	
	decl String:arg2[11];
	
	GetCmdArg(2, arg2, sizeof(arg2));
	
	if (StringToInt(arg2) == 1)
	{
		setQuery(arg1);
	}
	else
	{
		setQuery2(arg1);
	}
	
	return Plugin_Handled;
}

SQL.sp:
public setQuery(const String:sQuery[])
{
	SQL_FastQuery(g_hDb, sQuery);
	
	decl String:sError[1024];
	SQL_GetError(g_hDb, sError, sizeof(sError));
	LogToFile("randomlog.log", "Error: %s", sError);
}

public setQuery2(const String:sQuery[])
{
	SQL_TQuery(g_hDb, query2CallBack, sQuery, 1, DBPrio_Low);
}

public query2CallBack(Handle:owner, Handle:hndl, const String:error[], any:data)
{
	if(hndl == INVALID_HANDLE)
	{
		LogToFile("randomlog.log", "Error: %s", error);
		return;
	}
}

Results:
sm_query "SELECT * FROM `ck_playerrank`" 1 - Ran with SQL_FastQuery and timed out the plugin as expected.
sm_query "SELECT * FROM `ck_playerrank`" 2 - Ran with threading and didn't impact the server at all.

Overall, I knew how dangerous SQL_FastQuery could be with large tables for a while now, but I just wanted to make sure I provided enough proof that this was the issue. I hope in future updates, this can be changed to threaded. All the other Fast Queries in the sql.sp are harmless (small queries that won't affect much). Therefore, the only SQL_FastQuery needing a change is the one that selects the ck_playerrank table.

P.S. I tried formatting the code but it isn't working for me.

Thanks.

**Comment by jonitaikaponi** [comment]
Hey, those queries were only to check that the tables exist, so there really isn't need for threads here. I have since edited the code to a much lighter version.
