### ISSUE TITLE
Zones suggestion

### ISSUE THREAD

**Issue by anatoly-kussul** [jonitaikaponi/ckSurf#28]
Hey, I am really in love with your plugin, but i have some suggestions:

1) Is there any way to add TeleToStage zone type, which will teleport player to start of their current stage? Because there are some maps (e.g. staged maps with jail), where I don't want to teleport players on map start, and I don't want them to manually write !back all the time they got into jail.

2) In zone views options you have only 3 options, but I'd like too see only Start, End and Bonus zones, without seeing stage zones.

**Comment by jonitaikaponi** [comment]
1)) Use a validator zone
2) Not planned

**Comment by anatoly-kussul** [comment]
I'm sorry, but can you explain how I can use validator in thoose needs?

**Comment by jonitaikaponi** [comment]
Oops.. I meant the checker zone..

Just make a checker zone. Those will teleport back to the last stage, if
the player hasn't passed the validator zone.
30.10.2015 20.25 "anatoly-kussul" <notifications@github.com> kirjoitti:

**Comment by anatoly-kussul** [comment]
oh, I see now, thanks a lot. =)
