### ISSUE TITLE
Bug after first Record on a Map

### ISSUE THREAD

**Issue by cRUSHER-ScriptBase** [jonitaikaponi/ckSurf#3]
Hei, i have finished on a map who no one else has made a record / run and then this will apear then. Link: https://www.dropbox.com/s/sibf3zi92wa3vjl/2015-06-26%2019.43.15.jpg?dl=0
When i made the same map again then the rank is standing right with 1 / 1.

**Comment by jonitaikaponi** [comment]
Did you have any error logs? Might be a database issue.

2015-06-26 20:50 GMT+03:00 cRUSHER-ScriptBase <notifications@github.com>:

**Comment by cRUSHER-ScriptBase** [comment]
No i dont have any message all is working how its must. In the logs are nothing.

**Comment by jonitaikaponi** [comment]
Update ckSurf.smx
28.6.2015 0.56 "cRUSHER-ScriptBase" <notifications@github.com> kirjoitti:
