### ISSUE TITLE
Cringe worthy hook

### ISSUE THREAD

**Issue by nikooo777** [jonitaikaponi/ckSurf#34]
Hello,
So, there is a major problem with how the chat is processed. My server is not logging the chat anymore as the plugin is changing the way the text is printed and it's not letting it through the log file.

Therefore hlstatsx will not work to track chat either.

For this reason i was looking at the source code and opened up hooks.sp and looked at Say_Hook.

It makes me cringe, i'm sorry for whoever wrote it, but why on earth would anyone check char by char for triggers? I really don't understand that.

Let's take an example:
```
if (strlen(sText)>6 &&strlen(sText)<=9)
		{
			if (sText[0]=='!' && sText[1]=='s' && sText[2]=='t' && sText[3]=='a' && sText[4]=='g' && sText[5]=='e')
			{
				g_bSayHook[client]=false;
				return Plugin_Handled;
			}
		}
```
 this is some pure madness, let's code it somehow better:
``` 
if(StrEqual(sText,"!stage",false))
		{
			g_bSayHook[client]=false;
			return Plugin_Handled;	
		}
```

isn't it a bit better?

Please take some time to clean up that part of code and perhaps make sure that the chat is logged correctly to the file log as it's very important for server admins when investigating issues.

Greetings,
Niko

Edit: in case you're looking for a longer string... such as "!stage 5", then strequal will not return true, so it might be necessary to use 
```
StrContains(sText,"!stage",false)==0
```

as the substring !stage (non sensitive) will match at position 0.

Edit2: I *think* it would anyway be more wise to use RegConsoleCmd... http://sourcemod.net/new-api/console/RegConsoleCmd

**Comment by jonitaikaponi** [comment]
Hey,

That won't work becuase you can't know what the variable after !stage is
going to be.
Also you can use ck_chat_enable to disable ckSurf's chat processing.

2015-12-01 4:29 GMT+02:00 Niko <notifications@github.com>:

**Comment by nikooo777** [comment]
Hi, can you please read the edited message? After posting it i added some more information

**Comment by nikooo777** [comment]
Here is a possible example: 
https://github.com/nikooo777/ckSurf/commit/6478fc76fd24370b7eeb8fc674f3ac099a670fa4

**Comment by jonitaikaponi** [comment]
Added the suggestions you had for the chat triggers. If you want the chat logging, I'd look into HLStatsx's natives and check if there is a method to log chat messages.

**Comment by nikooo777** [comment]
nice, i checked your commit out and it looks already better :)

I will try and open some more issues so that you can improve your plugin

**Comment by jonitaikaponi** [comment]
Yes please!

There is a lot to check, especially when some of the code is straight from
KZTimer, my personal tests from when I started coding SP (this is my first
plugin) and from the time this plugin was just running on my server.

I was thinking of a complete recode for version 2.0, where the database
would also get a major overhaul, but those are just too big of changes to
make by myself. Another coder going through the code, would make this
process much much more simpel.

Cheers,
Joni
1.12.2015 4.56 ip. "Niko" <notifications@github.com> kirjoitti:

**Comment by nikooo777** [comment]
alright today i had 10 minutes to check out the code again and added logging function. 

add this to misc.sp:
```
stock WriteChatLog(client, const String:sayOrSayTeam[], const String:msg[1024])
{
	decl String:name[MAX_NAME_LENGTH];
	decl String:steamid[64];
	decl String:teamName[10];
	
	GetClientName(client, name, MAX_NAME_LENGTH);
	GetTeamName(GetClientTeam(client), teamName, sizeof(teamName));
	GetClientAuthString(client, steamid, sizeof(steamid));
	LogToGame("\"%s<%i><%s><%s>\" %s \"%s\"", name, GetClientUserId(client), steamid, teamName, sayOrSayTeam, msg);
}
```
and then in hook.sp in the say_hook at line ~210 under 
```
		TrimString(sText); 
```
add this
```
		WriteChatLog(client, "say", sText);
```
As easy as that.

Thank you

**Comment by jonitaikaponi** [comment]
Hey,

Good solution, just didn't really see a point in working on it, so I've
been focusing on other things.

Also don't know why you wrote it in the old syntax, as you really wanted to
change all code to the new syntax. Moved the WriteChatLog a little lower in
the say hook, so it won't log hidden chat commands.

Cheers

Joni

2015-12-09 0:59 GMT+02:00 Niko <notifications@github.com>:

**Comment by nikooo777** [comment]
hey i wrote it in the old syntax because i noticed that the master branch doesn't compile on sm 1.7. 
I wanted to implement that on my server and i'm using this branch so far.

But yeah it's quickly done to rewrite it :)

And yes, i just noticed that by having my log spammed with !r hahah.


aaand here it is converted for your convenience:

```
stock void WriteChatLog(int client, const char[] sayOrSayTeam, const char[] msg)
{
	char name[MAX_NAME_LENGTH];
	char steamid[64];
	char teamName[10];
	
	GetClientName(client, name, MAX_NAME_LENGTH);
	GetTeamName(GetClientTeam(client), teamName, sizeof(teamName));
	GetClientAuthString(client, steamid, sizeof(steamid));
	LogToGame("\"%s<%i><%s><%s>\" %s \"%s\"", name, GetClientUserId(client), steamid, teamName, sayOrSayTeam, msg);
}
```
