### ISSUE TITLE
regarding the last update

### ISSUE THREAD

**Issue by nikooo777** [jonitaikaponi/ckSurf#36]
Hey,
as described here: https://forums.alliedmods.net/showthread.php?t=275847

it appears that the function takes very long to reach that specific point and the client might not be valid anymore (i guess), therefore i would suggest you to check again for the player validity by adding before PrintConsoleInfo this:

```
	//it takes time to reach this part of the function, hence the client might not be valid anymore
	if (!IsValidClient(client) || IsFakeClient(client))
	{
		return;
	}
```

Greetings,
Niko

**Comment by jonitaikaponi** [comment]
Hey,

Hmm.. Im suspecting that the CS_SetClientName in misc.sp is causing this
issue also. It seems to have broken, and caused the issue with record bots
after the update.

I switched the CS_SetClientName to SetClientName and added the check that
you suggested also. We'll see if it is fixed now.

Cheers,
Joni

2015-12-10 3:45 GMT+02:00 Niko <notifications@github.com>:

**Comment by nikooo777** [comment]
i just crashed twice with that fix i suggested so i guess it's something else too. I didn't try your patch now so let me see if that works.

Also nice to see you up at this time in the night!

**Comment by jonitaikaponi** [comment]
Yeah, working on other things.. Going to be an all nigher I think :).
School, work and plugin keeps ya busy

2015-12-10 3:58 GMT+02:00 Niko <notifications@github.com>:

**Comment by nikooo777** [comment]
don't tell me... i have to be at uni in 5 hours...

Anyway i think i'm screwed, can't compile SetClientName on sm1.6 apparently. Do you have the same issues by any chances?

**Comment by jonitaikaponi** [comment]
Yup, that doesn't seem to be in that old of an verion of SM. Got to figure
out another way I guess.

Don't have time for that for now, but 1.8b has the new fix.

2015-12-10 4:04 GMT+02:00 Niko <notifications@github.com>:

**Comment by nikooo777** [comment]
alright i will be upgrading tomorrow morning during class...
Will i lose the records or anything during the upgrade process?

**Comment by jonitaikaponi** [comment]
Nope, Just give it enough time to make all the changes without players
connecting. It might take a while on huge databases.

2015-12-10 4:28 GMT+02:00 Niko <notifications@github.com>:

**Comment by nikooo777** [comment]
understood, thanks!

Since i'll move to 1.18 i'll stop checking for issues on 1.17 and directly work on the new one to try and get it a bit smoother :)

Goodnight!

**Comment by psychonic** [comment]
> can't compile SetClientName on sm1.6 apparently.

The stable SM 1.7 builds have had this for a long time (as well as the developer 1.8 builds).
