### ISSUE TITLE
Trigger Problem

### ISSUE THREAD

**Issue by heatoff** [jonitaikaponi/ckSurf#39]
Teleport trigger 't26' cannot find destination named 't2626'!
Anyone can help me? It happening after update

**Comment by jonitaikaponi** [comment]
Doesn't sound like a ckSurf issue. When does this happen?
13.12.2015 11.50 ap. "heatoff" <notifications@github.com> kirjoitti:

**Comment by heatoff** [comment]
When someone entering the teleport to stage 2 etc.

**Comment by jonitaikaponi** [comment]
This sounds like an issue in the map, not in the plugin
13.12.2015 11.55 ap. "heatoff" <notifications@github.com> kirjoitti:

**Comment by heatoff** [comment]
Propably because on other maps it doesn't happening. Thank you very much for fast response.

**Comment by jonitaikaponi** [comment]
No problem.
13.12.2015 11.58 ap. "heatoff" <notifications@github.com> kirjoitti:
