### ISSUE TITLE
Zone editing doesn't match (version. Commit 90)

### ISSUE THREAD

**Issue by minh9956** [jonitaikaponi/ckSurf#40]
Hello,

When I try to edit a zone (!zone --> 2. Edit Zones --> 1. Normal Map Zones), sometimes the the zones don't match up. So say I want to edit "Stage-0", on the next page it's actually "Editing Zone: Stage-2". If you try to Goto zone, it is Stage-2. This particular example is from surf_molstration.

I've tested this with the database provided in cksurf 1.17 and 1.18b and they both have the same problem. The cksurf files I currently have are from 1.18b commit 90 so I don't know if this has been solved after the merge.

**Comment by jonitaikaponi** [comment]
Hey,

This is a known issue. I'll look for a fix soon.
13.12.2015 1.26 ip. "Minh Tran" <notifications@github.com> kirjoitti:

**Comment by minh9956** [comment]
Cool cool thanks.

While you're at it, perhaps in the Stretch zone menu you could swap, +/- Height and +/- Length, as length is actually editing the height of the box

**Comment by jonitaikaponi** [comment]
Sure thing. Just post all the issues you find in it. There are some issues
in editing and the logic of the menu. Sometimes pressing back goes too far
back, sometimes selected zones don't get unselected etc.
13.12.2015 1.51 ip. "Minh Tran" <notifications@github.com> kirjoitti:
