### ISSUE TITLE
Stages are now marked Bonus

### ISSUE THREAD

**Issue by knackrack615** [jonitaikaponi/ckSurf#41]
Hello, after the last csgo update i updated both sourcemod and cksurf and all of a sudden every stage on every map is now marked as bonus..

Also the map reply bot doesn't work anymore (It just spawns a random bot with localhost in its name)

Sourcemod - Tools version(s):

 [01] SourceMod (1.8.0.5801) by AlliedModders LLC
 [02] CS Tools (1.8.0.5801) by AlliedModders LLC
 [03] SDK Tools (1.8.0.5801) by AlliedModders LLC
 [04] DHooks (2.0.2) by AlliedModders
 [05] SDK Hooks (1.8.0.5801) by AlliedModders LLC

ckSurf Version: 
28 "ckSurf" (1.17) by Elzi

Example error log for a staged map: http://hastebin.com/cexuwedale.coffee

**Comment by jonitaikaponi** [comment]
"28 "ckSurf" (1.17) by Elzi"

You have to update to 1.18b. Also make sure to wait enough time before
connecting to your server after setting the 1.18b .smx file (look at the
server console, to see when it is safe to connect)

2015-12-13 16:47 GMT+02:00 knackrack615 <notifications@github.com>:

**Comment by knackrack615** [comment]
Alright, i've upgraded to 1.18b and now everything works fine except 1 map (surf_eclipse)
The map has 2 stages but they're marked as speedzone's

If i try to edit them this happens

L 12/13/2015 - 15:59:55: Info (map "surf_eclipse_hgc") (file "errors_20151213.log")
L 12/13/2015 - 15:59:55: [ckSurf.smx] [ckSurf] SQL Error (db_checkAndFixZoneIdsCallback): near ",": syntax error
L 12/13/2015 - 16:00:00: [ckSurf.smx] [ckSurf] SQL Error (db_checkAndFixZoneIdsCallback): near ",": syntax error
L 12/13/2015 - 16:00:08: [ckSurf.smx] [ckSurf] SQL Error (db_checkAndFixZoneIdsCallback): near ",": syntax error

**Comment by jonitaikaponi** [comment]
Sounds like the server didn't have enough time to make all the changes
before you changed map or connected.

The only real solution to this is to revert back to your 1.17 database,
start the server with the 1.18 plugin and wait for the server to do the
changes to your database, like it says in the installation instructions.
13.12.2015 5.04 ip. "knackrack615" <notifications@github.com> kirjoitti:

**Comment by knackrack615** [comment]
Nevermind, i've fixed it by opening the database with an SQLite browser and deleting the surf_eclipse record from ck_zones

**Comment by jonitaikaponi** [comment]
I can guarantee that you will have the same issue in other maps.

One solution is to run !insertmapzones again, but it will delete zones that
you have made.
13.12.2015 5.13 ip. "knackrack615" <notifications@github.com> kirjoitti:

**Comment by knackrack615** [comment]
Nope, all other staged maps work fine

The problem with surf_eclipse is probably cause because i've re-created the zones with the bugged version of ckSurf

**Comment by knackrack615** [comment]
Hey, um do you have steam? i would prefer talking there

**Comment by jonitaikaponi** [comment]
Sorry, but I don't add people regarding the plugin on steam
13.12.2015 5.33 ip. "knackrack615" <notifications@github.com> kirjoitti:

**Comment by knackrack615** [comment]
Ah, i see.. well right now the problem is, when i try to save all zones it deletes every zone in the current map

There are no error messages on the console tho

**Comment by jonitaikaponi** [comment]
Try to reload zones after that from the !zones menu.
13.12.2015 5.36 ip. "knackrack615" <notifications@github.com> kirjoitti:

**Comment by knackrack615** [comment]
Alright, reloading after saving works :)

Thanks
