### ISSUE TITLE
Timer does not start when use !r

### ISSUE THREAD

**Issue by Seenko** [jonitaikaponi/ckSurf#42]
Some users were complaining that when you are surfing and you do !r, when you exit the start zone the timer does not start, it only does when you go back in the zone again and exit, then it starts properly.

Maybe when you use !r you're just stopping the timer but not telling that the timer is stopped, so when you enter the zone again, then it actually stops the timer and works properly after that.

**Comment by jonitaikaponi** [comment]
When have you updated? This was fixed some time ago.

2015-12-14 20:52 GMT+02:00 Seenko <notifications@github.com>:

**Comment by Seenko** [comment]
By the time users were telling me that, I was using commit 103 (from yesterday).

**Comment by jonitaikaponi** [comment]
This was fixed 3 days ago in
https://github.com/jonitaikaponi/ckSurf/commit/bde203f8ff6c2e7de25b525d7b92401a91fede0d
.

The code has changed since, but I can't get that bug to happen on the
newest version either.

2015-12-14 20:56 GMT+02:00 Seenko <notifications@github.com>:

**Comment by 4everGhost** [comment]
For my servers it was fixed with the update from Dec 13, 2015 (yesterday) and no complains anymore.

**Comment by nikooo777** [comment]
i might have reproduced it once by reloading the plugin while surfing a staged map. once i was teleported back to the start zone (i think i used !r) i couldn't get the timer to start on the first try. 

I tried to reproduce that once more but it worked without errors hence I thought it was just a bad coincidence of timings in the commands i issued.

Can anybody reproduce it? Using what steps?
