### ISSUE TITLE
Critical issue with new update.

### ISSUE THREAD

**Issue by heatoff** [jonitaikaponi/ckSurf#46]
My server doesn't respond and crashin cause thise.
L 12/24/2015 - 13:57:16: [SM] Displaying call stack trace for plugin "cksurf.smx":
L 12/24/2015 - 13:57:16: [SM] [0] Line 3395, ckSurf/misc.sp::Checkpoint()
L 12/24/2015 - 13:57:16: [SM] [1] Line 237, ckSurf/surfzones.sp::StartTouch()
L 12/24/2015 - 13:57:16: [SM] [2] Line 109, ckSurf/surfzones.sp::StartTouchTrigger()

**Comment by jonitaikaponi** [comment]
Sounds like maybe you are missing the translation file?

**Comment by heatoff** [comment]
Translation file is updated.
