### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by MZDisaster** [jonitaikaponi/ckSurf#5]
Am I missing something?

http://paste.ubuntu.com/11815612/

**Comment by marcowmadeira** [comment]
Use an old version of sourcemod. You can download it [here](http://www.sourcemod.net/smdrop/1.6/).

**Comment by MZDisaster** [comment]
is there a specific version i need?

**Comment by marcowmadeira** [comment]
I'm not sure, i can compile it using 1.6.4, but the others should still work.

**Comment by MZDisaster** [comment]
ok, thanks.
