### ISSUE TITLE
Timer disappears after record

### ISSUE THREAD

**Issue by entrailz** [jonitaikaponi/ckSurf#56]
With the most recent push to Github - when you complete a map your timer disappears, and on reconnect to the server the bot does not start the replay file.

**Comment by zAfLu** [comment]
Yeah, same for me.

Tested with my pull requests -> works fine
Tested recent commites -> disappears after map finish. 

Looks like the timer is working fine in the background but the visual stuff in the info box is gone.

**Comment by jonitaikaponi** [comment]
Yeah, its due to a variable that I changed when clearing code, updating in
a sec.

2016-01-08 12:58 GMT+02:00 zAfLu <notifications@github.com>:
