### ISSUE TITLE
1.17 to 1.18 Database issues 

### ISSUE THREAD

**Issue by RavageCS** [jonitaikaponi/ckSurf#57]
Going from 1.17 to 1.18 many maps zones are corrupted. Some maps load, but checkpoints are set to bonus stage. This is a particular problem because there is no way to change a bonus zone to a regular zone. Some maps the zones don't load at all with error in logs as:

[SM] Exception reported: Array index is out of bounds
[SM] Blaming: ckSurf.smx()
[SM] Call stack trace:
[SM]   [1] Line 4923, ckSurf/sql.sp::checkZoneTypeIdsCallback()

**Comment by jonitaikaponi** [comment]
This has been adressed here already: https://github.com/jonitaikaponi/ckSurf/issues/41

Also, you seem to be running an old version, as the code where you got the error has been commented out for a while now.

**Comment by RavageCS** [comment]
Restored to a 1.17 backup then ran https://github.com/jonitaikaponi/ckSurf/blob/1.18-Beta/Optional%20files/Database%20files/1.17%20to%201.18.sql All seems to be working again, not sure why theses errors were happening, but is solved. Plugin version was always 1.18, was not running an old version, only the database files were buggy.
