### ISSUE TITLE
Last Seen is borken

### ISSUE THREAD

**Issue by zAfLu** [jonitaikaponi/ckSurf#59]
Hi,

looks like the "Last seen" is currently borken. New player get "NULL" in database and "old" players still stick on old data

**Comment by jonitaikaponi** [comment]
Should be updated when finishing a map.

**Comment by zAfLu** [comment]
No, isn't working. Tested it 3 days long :)

**Comment by jonitaikaponi** [comment]
Pretty sure it was fixed here?
https://github.com/jonitaikaponi/ckSurf/commit/967862280d9736370ccb96a29db215cba3dff241#diff-4b6a46c98935534b19e8096e3117e6c8R1242
Please test before you claim otherwise.

**Comment by zAfLu** [comment]
I can test again with the newst commit, give me some minutes :)

**Comment by zAfLu** [comment]
ah ok looks like itsfixed now. nvm sry
