### ISSUE TITLE
ck_chat_record_type does not function.

### ISSUE THREAD

**Issue by blackhawk74** [jonitaikaponi/ckSurf#65]
Tested only using ck_chat_record_type 1, it announces zero records but announces points gains.

**Comment by jonitaikaponi** [comment]
Should be fixed now

**Comment by blackhawk74** [comment]
Still does not work unfortunately

**Comment by blackhawk74** [comment]
Did some further testing. Displays times when there are time improvements (ex. beating a map in 2 minutes when previous record was 4), but does not display a new map record, for players who have not beaten the map prior to that one completion.

**Comment by blackhawk74** [comment]
Fixed now, thanks!
