### ISSUE TITLE
Issue with Checkpoint chat timer showing 00:00:00

### ISSUE THREAD

**Issue by gwpc** [jonitaikaponi/ckSurf#67]
First let me say thank you for this excellent plugin. 

I'm having an issue where the checkpoint progress to chat is showing 00:00:00 like this:

[CK] CP: Completed 33% of the map in 00:00:00.

However, I'd rather just remove this being printed to chat period. How would I go about doing this?

Thanks for your time.

**Comment by gwpc** [comment]
This seems to be happening when I disable the Speed/Stage panel via !options

**Comment by jonitaikaponi** [comment]
You can also disable checkpoints in the !options menu. Ill look into the
time issue later.
16.1.2016 7.49 ap. "gwpc" <notifications@github.com> kirjoitti:

**Comment by gwpc** [comment]
Thanks for your prompt response.

It seems I'm having issues with the last two pages of the !options menu. When I choose option 5 I get option 4, choose 4 get 3, etc. 

Also: How would I disable it globally for all players?

**Comment by jonitaikaponi** [comment]
Seems that you had autobhop disabled, the menu and checkpoints should work fine now.

You can't disable them globally without changing the code.

**Comment by gwpc** [comment]
You're the man.

I just updated to the latest code and now I can't select any options in the !options menu. I select them but their state does not change.

**Comment by jonitaikaponi** [comment]
Ah my bad, left some code there that wasn't supposed to be there. Should work in the newest

**Comment by gwpc** [comment]
That fixed it. Although now I have a new problem. I have to !insertmaptiers and !insertmapzones on server restart or they do not load. Switching to MySQL from sqlite did not resolve the issue.

**Comment by jonitaikaponi** [comment]
Update to the latest version, if you are using workshop maps
17.1.2016 11.23 "gwpc" <notifications@github.com> kirjoitti:

**Comment by gwpc** [comment]
I am not using workshop maps currently. I updated to the latest version and have the same problem.

**Comment by gwpc** [comment]
Did a fresh install and seems to be working. Thanks for all of your help.

**Comment by gwpc** [comment]
Tried a fresh install with the latest code. I get the same problem on server restart

**Comment by jonitaikaponi** [comment]
Tested on MySQL and SQLite, works fine.

Make sure your map names don't have capital letters, as map names are case sensitive. If it still doesn't work, make sure your database has the zone data in the ck_zones table.

**Comment by gwpc** [comment]
Strange. It seems to only happen on the first map on server restart. If I reload the same map via rcon the zones work fine. I don't think there's a discrepancy in my mapcycle.txt and my +map parameter in server launch: +map surf_kitsune and it's spelled the same way in mapcycle.txt
