### ISSUE TITLE
Zone flag not working properly

### ISSUE THREAD

**Issue by PrinceDrew** [jonitaikaponi/ckSurf#69]
I set the access to zone flag to "m" for rcon access, but no matter what, people with the m flag can't use it. I checked the code and it seems to be fine, but it wont work for some reason. I changed the access to ckadmin to "m" an that works just not zones.

**Comment by jonitaikaponi** [comment]
Tested with admin flag m and ck_zonemenu_flag "m" and worked fine.

The command requires a server restart for it to take effect.

**Comment by PrinceDrew** [comment]
Weird I was having issues with it last night. I finally just hardcoded the sm_zones command to ADMFLAG_RCON and it worked.
