### ISSUE TITLE
Respawn on server loading not working

### ISSUE THREAD

**Issue by Kryptanyte** [jonitaikaponi/ckSurf#70]
If the server still stuck loading stats you can't respawn even though the zones have already loaded in.

Using !end and !bonus work however.

I mentioned this in another issue but I'll say it again here. Sometimes my servers take longer than a minute to load. This gets worse the more players there are on the server, could this be due to the amount of things being pulled by cksurf or will it most likely be a sql throttling issue?

**Comment by jonitaikaponi** [comment]
The loading depends on your database connection. Basically the plugin loads your server's settings first, and then starts to load player settings. If you have a high latency or load on your database, then it will take longer.
