### ISSUE TITLE
Another issue with bonuses

### ISSUE THREAD

**Issue by alerad** [jonitaikaponi/ckSurf#71]
Hey, i've found yet another issue with bonuses, sometimes people get flagged as record holders when they make the bonus in less time than the record. 

Example:

Was playing the bonus of stonework2, guy #1 (record holder) had 7:05s record, guy #2 comes and does 7:45s, bonus record sound plays on the server + says guy #2 got the record and the bot gets replaced. 

Happened on a few other maps which i can't recall at the moment.

Maybe add a validation that says that someone can't get a record if it's lower than #1 as a temporary work arround + security check? I'm not sure in which file getting records is defined, if not i'd try to add it :/

**Comment by jonitaikaponi** [comment]
This was due to a bad comparison in an sql statement, should work fine now.

**Comment by alerad** [comment]
Thank ye
