### ISSUE TITLE
replay bot not recording

### ISSUE THREAD

**Issue by nikooo777** [jonitaikaponi/ckSurf#72]
Hi,
I'd like to report an issue that i'm seeing on my servers:
I have one database shared with many gameservers around the world, each machine is responsible for recording and saving its own records, that means that the server in the US might have a certain map recorded where the EU server has another.

Example:

US (surf_mesa): player_X (45s)
EU (surf_mesa): Player_Y (46s)

Upon deleting the recorded files i noticed that the .rec files are not generated anymore. Is the recording only happening and saving if the player sets a world record? Can this be adjusted to save a recording if there is not a previous one saved?

I am running the very latest version.

Thank you and best regards,
Niko

**Comment by jonitaikaponi** [comment]
Hey

Yes. Recordings only happen, if the player gets the new SR.

I am currently working on a patch, that will allow bots to be created if
there is no record bot, or if someone beats the record bot's time. The
patch also fixes the remaining issues with the record bot getting out of
sync, adds bots to multiple bonuses  (the bot will go through all of them
one by one)  and allows backing up of recordings.

This patch also adds a mute player option for VIP's (this can be disabled)
and issues with godmode, ck_round_end are also fixed.

The patch will be up later today or tomorrow.
24.1.2016 2.00 ip. "Niko" <notifications@github.com> kirjoitti:

**Comment by nikooo777** [comment]
Hey,
Thank you! this seems like good news for us server owners :)
Thanks for working on it.

Niko

**Comment by nikooo777** [comment]
i see the issue was fixed!
the patch seems to work. good job.

I'll close this.
