### ISSUE TITLE
God mode problem

### ISSUE THREAD

**Issue by AticZPrime** [jonitaikaponi/ckSurf#75]
// on/off - unlimited hp
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
ck_godmode "0"

// Sets HP amount for autohealing (requires ck_godmode 0)
// -
// Default: "50"
// Minimum: "0.000000"
// Maximum: "100.000000"
ck_autoheal "0

The only damage that appears to be working is fall damage. I tried using this plugin with my course server and everything works fine except the godmode and autoheal. I tried disabling them but the map does not do any damage that is supposed to do.

**Comment by jonitaikaponi** [comment]
Thats because the plugin disables trigger_hurts. I removed the disabling from the newest version, as it is pretty useless for surf_
