### ISSUE TITLE
Timer Glitch

### ISSUE THREAD

**Issue by apatcheeee** [jonitaikaponi/ckSurf#8]
Hey, so recently people have found a new glitch on CKsurf, it basically allows people to teleport to the last stage with a timer running.

A friend showed me how to do it, https://www.youtube.com/watch?v=hhkA1mWINgY&feature=youtu.be

      s p o o k y: ok
      s p o o k y: it requires 2 people
      s p o o k y: heres what you do, i get on stage 5
      s p o o k y: then you type !s 5 you dont have to have timer running
      s p o o k y: when you are on !s 5 you type !spec s p o o k y
      s p o o k y: when you are spectating me, you type !r
      s p o o k y: do stage 1, and stand at the start of stage 2, make sure your time is running
      s p o o k y: then type kill in the console
      s p o o k y: spam spacebar
      s p o o k y: you will spawn on stage 5 with your timer running.

Thanks

**Comment by jonitaikaponi** [comment]
Should be fixed now.

2015-07-08 8:07 GMT+03:00 apatcheeee <notifications@github.com>:
