### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by kyleman526** [jonitaikaponi/ckSurf#81]
Currently my server is fully working with CKsurf working and ready to go, but the problem im having is that the map doesn't change until someone beats it and the map rotation doesn't work. So essentially the map doesn't change at all and i need a timer set so it changes the map appropriately.

**Comment by Technoblazed** [comment]
The chances are you're not using an appropriate map changing plugin such as map chooser provided with sourcemod. Feel free to add me on steam to discuss further http://steamcommunity.com/id/Technoblazed
