### ISSUE TITLE
SteamCMD can't find maps / Automatically switch maps after player login

### ISSUE THREAD

**Issue by O113** [jonitaikaponi/ckSurf#83]
Hi! 

I'm trying to figure this one out, but I really don't get what's happening. After installing cksurf and using the maps found at AlliedMods, I'm unable to load any of the maps in the pack and the game starts with dust and instantly change map to the next in the mapcycle. 

Any idea what's going on? 

Thanks!

**Comment by jonitaikaponi** [comment]
Did you extract the .bz2 files? Error logs? Did you add the maps to your mapcycle.txt? What does your server respond when you write "maps surf_" into the server console?

**Comment by O113** [comment]
man, now I feel like an idiot, I did not extract them, I'll get right on it and recreate the mapcycle for safety measures. Thank you.
