### ISSUE TITLE
!top issue

### ISSUE THREAD

**Issue by kyleman526** [jonitaikaponi/ckSurf#86]
Copied my server for a friend and he wants a fresh Top 100

So basically i want to clear out the Top 100 players when i type !top. How would i delete that saved data?

**Comment by Technoblazed** [comment]
Drop your playerrank database as shown in the admin cvars here:

https://forums.alliedmods.net/showthread.php?t=264498

**Comment by jonitaikaponi** [comment]
You have to clear the database. Depends on your settings. If you are using sqlite, then just rename the file at addons/sourcemod/data/sqlite/, if you are using MySQL, clear the tables.
