### ISSUE TITLE
Setting a new map record changes the map to the default one.

### ISSUE THREAD

**Issue by samosnik** [jonitaikaponi/ckSurf#87]
When i install a new map and beat the record on it. It changed back to the default map. Any tips?

**Comment by marcowmadeira** [comment]
It's probably because you didn't have the .nav file. After beating the record, the plugin will add the bot and if you don't have the .nav file for that map, the game will generate the file and change the map.

**Comment by samosnik** [comment]
Ah that makes perfect sense! I see that the .nav files have been generated for the record bot! Thank you very much!
