### ISSUE TITLE
SourceMod Errors (one leading to server crash)

### ISSUE THREAD

**Issue by gamemann** [jonitaikaponi/ckSurf#9]
Hello, I've seen a few SourceMod errors spamming the server. One I have seen before and leads to a server crash (this was a bug in KZTimer), the other appears to be somewhat harmless.

Error 1 (harmful):
L 07/09/2015 - 20:58:17: [SM] Native "PushArrayArray" reported: Failed to grow array
L 07/09/2015 - 20:58:17: [SM] Displaying call stack trace for plugin "ckSurf.smx":
L 07/09/2015 - 20:58:17: [SM]   [0]  Line 591, ckSurf/replay.sp::RecordReplay()
L 07/09/2015 - 20:58:17: [SM]   [1]  Line 620, ckSurf/hooks.sp::OnPlayerRunCmd()

I remembering seeing this error a long time ago and this eventually crashes the server.
For more information, look here: https://forums.alliedmods.net/showthread.php?t=260754
This is still not fixed in the KZTimer plugin. However, it may still be worth looking into.

Error 2 (harmless):
L 07/09/2015 - 20:58:17: [SM] Plugin encountered error 22: Maximum number of parameters reached
L 07/09/2015 - 20:58:17: [SM] Native "PrintToChat" reported: Translation string formatted incorrectly - missing at least 3 parameters
L 07/09/2015 - 20:58:17: [SM] Displaying call stack trace for plugin "ckSurf.smx":
L 07/09/2015 - 20:58:17: [SM]   [0]  Line 2439, ckSurf/misc.sp::Checkpoint()
L 07/09/2015 - 20:58:17: [SM]   [1]  Line 200, ckSurf/surfzones.sp::StartTouch()
L 07/09/2015 - 20:58:17: [SM]   [2]  Line 112, ckSurf/surfzones.sp::StartTouchTrigger()

These issues occur with the latest version of the timer. I hope they can be addressed and fixed.

Thanks.

**Comment by jonitaikaponi** [comment]
Hey,

The 1st is a bug that really doesn't have a solid fix. I'll try to code a
reset on the record bots every 30 minutes and see if that would fix it.

The 2nd error seems to be because you didn't update your translate file,
when updating the plugin.

2015-07-09 22:46 GMT+03:00 Christian Deacon <notifications@github.com>:

**Comment by gamemann** [comment]
Hello, I am sorry for the false report on error 2. 

Thanks.
