### ISSUE TITLE
Timer Issue (Database)

### ISSUE THREAD

**Issue by Shoxxo** [jonitaikaponi/ckSurf#90]
The Timer from the Database will not work correctly...

**Comment by jonitaikaponi** [comment]
What? 0 info 0 error logs?

**Comment by Shoxxo** [comment]
What... Read what i say, bad admin

**Comment by jonitaikaponi** [comment]
"The Timer from the Database will not work correctly..."

Not really much to work on.

**Comment by iNickb21** [comment]
it works fine for everyone but you shoxxo... read what he said and give us error logs
